import { describe, expect, it } from 'vitest';
import * as path from 'path';

/**
 * `tools/corpus-harness/ceiling.js` is the instrument behind R4's language choice (design §3.7,
 * DECISIONS §82). It checks itself at run time — every node type it names must exist in the
 * grammar, every known-answer fixture must pass, and on the shipped languages `--parity` must
 * reproduce core's `selectElisionRegions` file for file — but those checks need grammar WASM that
 * this repository does not install for the candidates. What can be pinned without a grammar is
 * pinned here:
 *
 *  - **the pre-registered floor**, so moving it after results exist is a visible diff rather than
 *    an edit to a constant;
 *  - **classification**, which had to be corrected twice before any candidate was measured —
 *    each case below marked *found in a tree* was read out of a real corpus, not imagined;
 *  - **the independent lexer** that vouches for region boundaries where the grammar left ERROR
 *    nodes;
 *  - **that every candidate's fixture set can fail in both directions** — a fixture set with only
 *    empty expectations passes an instrument that finds nothing.
 *
 * Loaded with `require`, the way `corpus-harness-timing.test.ts` reaches `timing.js`: `tools/` is
 * outside `tsconfig.json`'s `include`.
 */
// eslint-disable-next-line @typescript-eslint/no-require-imports
const ceiling = require(path.join(__dirname, '..', '..', 'tools', 'corpus-harness', 'ceiling.js')) as {
  FLOOR: number;
  LANGUAGES: Record<
    string,
    {
      exts: string[];
      stripAs: string;
      shipped?: boolean;
      functions?: string[];
      closures?: string[];
      braceTypes?: string[];
      endStyle?: string[];
      commentTypes?: string[];
    }
  >;
  FIXTURES: Record<string, Array<{ name: string; src: string; expect: string[]; fnOnly: string[] }>>;
  classify(relPath: string, content: string): 'source' | 'test' | 'generated';
  dropOverlapping(regions: ReadonlyArray<{ start: number; end: number }>): Array<{ start: number; end: number }>;
  lexBalanced(text: string): boolean;
};

describe('ceiling instrument — the pre-registered floor', () => {
  it('is 40% of source bytes, as registered before any candidate was measured', () => {
    // Moving this is changing the rule after seeing the data. DECISIONS §82 records when and by
    // whom it was set; a change here needs a new entry, not an edit.
    expect(ceiling.FLOOR).toBe(0.4);
  });
});

describe('ceiling instrument — classification', () => {
  const cases: Array<[string, string, 'source' | 'test' | 'generated']> = [
    ['plain source', 'guava/src/com/google/common/base/Strings.java', 'source'],
    ['Maven test tree', 'core/src/test/java/hudson/FooTest.java', 'test'],
    ['hyphenated test module', 'guava-tests/test/com/google/common/X.java', 'test'],
    ['Go-style suffix', 'absl/strings/str_cat_test.cc', 'test'],
    ['RSpec', 'spec/rubocop/cop/style_spec.rb', 'test'],
    // Found in a tree: Kotlin/Gradle source sets have no separator before `Test`.
    ['camelCase source set (okhttp)', 'okhttp/src/jvmTest/kotlin/okhttp3/CallTest.kt', 'test'],
    // Found in a tree: .NET test project whose name ends in `FuzzTests`.
    ['.NET FuzzTests project', 'Newtonsoft.Json.FuzzTests/FuzzTests.cs', 'test'],
    // Found in a tree: the Rust stdlib keeps its tests in `alloctests` and `coretests`.
    ['rust stdlib alloctests', 'alloctests/tests/vec.rs', 'test'],
    ['rust stdlib coretests', 'coretests/benches/iter.rs', 'test'],
    // The trap the case-sensitive rule exists for: `/i` would read `latest` as a test directory.
    ['latest/ is not a test dir', 'latest/release_notes.rs', 'source'],
    ['contest.go is not a test file', 'pkg/contest.go', 'source'],
    ['designer file by name', 'Migrations/Initial.Designer.cs', 'generated'],
  ];

  it.each(cases)('%s', (_label, relPath, want) => {
    expect(ceiling.classify(relPath, 'fn main() {}\n')).toBe(want);
  });

  it('reads generated-file headers, including stdarch\'s DO NOT MODIFY', () => {
    // Found in a tree: stdarch's generated intrinsics say "DO NOT MODIFY", not "DO NOT EDIT".
    expect(ceiling.classify('core_arch/src/x86/generated.rs', '// This code is automatically generated. DO NOT MODIFY.\n')).toBe(
      'generated',
    );
    expect(ceiling.classify('pb/x.go', '// Code generated by protoc-gen-go. DO NOT EDIT.\n')).toBe('generated');
    expect(ceiling.classify('X.cs', '// <auto-generated />\nclass X {}\n')).toBe('generated');
    expect(ceiling.classify('lib.rs', '// @generated\n')).toBe('generated');
  });

  it('does not call a file generated for a header it lacks — windows-sys is the recorded blind spot', () => {
    // windows-sys is machine-generated per its README, and none of its 249 files carries a
    // marker. File-level classification cannot see it; §82 reports it as a sensitivity instead.
    expect(ceiling.classify('src/Windows/Win32/UI/mod.rs', 'windows_link::link!("user32.dll" "system" fn F());\n')).toBe(
      'source',
    );
  });
});

describe('ceiling instrument — the independent brace lexer', () => {
  it.each([
    ['plain nested block', 'if (x) { a(); }', true],
    ['a closing brace too many', 'a(); }', false],
    ['an opening brace too many', '{ a();', false],
    ['brace in a string', 's = "}{";', true],
    ['brace in a char literal', "c = '{';", true],
    ['brace in a line comment', '// }\nx();', true],
    ['brace in a block comment', '/* { */ x();', true],
    ['brace in a C++ raw string', 'auto s = R"({"k": "}"})";', true],
    ['brace in a C# verbatim string with a doubled quote', 'var s = @"a "" }";', true],
  ])('%s', (_label, text, want) => {
    expect(ceiling.lexBalanced(text)).toBe(want);
  });
});

describe('ceiling instrument — dropOverlapping', () => {
  it('keeps the outer of a nested pair and the later disjoint region', () => {
    // Core's own copy is private to regions.ts; `--parity` proves this one equals it over every
    // file of the frozen corpus. This pins the rule itself.
    expect(ceiling.dropOverlapping([{ start: 2, end: 5 }, { start: 0, end: 10 }, { start: 12, end: 20 }])).toEqual([
      { start: 0, end: 10 },
      { start: 12, end: 20 },
    ]);
  });
});

describe('ceiling instrument — the fixture sets can fail both ways', () => {
  const candidates = Object.entries(ceiling.LANGUAGES).filter(([, spec]) => !spec.shipped);

  it('covers every candidate language', () => {
    expect(candidates.map(([name]) => name).sort()).toEqual(Object.keys(ceiling.FIXTURES).sort());
  });

  it.each(candidates.map(([name]) => [name]))('%s has positive and negative known answers', (name) => {
    const fixtures = ceiling.FIXTURES[name]!;
    expect(fixtures.length).toBeGreaterThanOrEqual(3);
    // At least one fixture that must find a region: an instrument that finds nothing fails it.
    expect(fixtures.some((f) => f.expect.length > 0)).toBe(true);
    // At least one that must find none: an instrument that takes everything fails it.
    expect(fixtures.some((f) => f.expect.length === 0)).toBe(true);
    // Every expected region text is literally present in its source, by construction.
    for (const fixture of fixtures) {
      for (const body of fixture.expect) expect(fixture.src.includes(body)).toBe(true);
    }
  });

  it.each(candidates.map(([name, spec]) => [name, spec] as const))('%s names a stripper core has', (_name, spec) => {
    expect(['typescript', 'python', 'go']).toContain(spec.stripAs);
    expect(spec.functions?.length ?? 0).toBeGreaterThan(0);
    expect((spec.braceTypes?.length ?? 0) + (spec.endStyle?.length ?? 0)).toBeGreaterThan(0);
  });
});
